### PR TITLE
Process arbitrary template tags in nodes

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
I've rebased this PR so that it only reflects the 1 commit

**Comment by EliotBerriot** [comment]
This looks really cool, thank you!

**Comment by EliotBerriot** [comment]
@wgordon17 I've pushed the 0.7 release to PyPi which includes all your changes :)

https://pypi.org/project/django-navutils/0.7/

**Comment by wgordon17** [comment]
@EliotBerriot Great! Thank you =)

**Pull request merged**
