### PR TITLE
Allow global template override

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Is this really needed? 

I thin. [django had a built-in way to support template overrides](https://docs.djangoproject.com/en/2.1/howto/overriding-templates/#overriding-from-an-app-s-template-directory).

Creating a `yourproject/yourapp/templates/navutils/menu.html` file should replace the one from navutils?

**Comment by wgordon17** [comment]
🤦‍♂️ You're absolutely right! Give me a bit, and I'll switch this PR to a PR on `README.md`...it can't hurt to include it in the docs for when people like me forget =)

**Comment by wgordon17** [comment]
@EliotBerriot There we go, now it's just a simple README update ;)

**Comment by EliotBerriot** [comment]
:ok_hand: thank you for the update :)

**Pull request merged**
